version: "3.8"
services:
  server:
    container_name: pr1_server
    build: test
    volumes:
      - ./test:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./test/init.sql:/docker-entrypoint-initdb.d/init.sql"
